/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef DebugProtoTest_CONSTANTS_H
#define DebugProtoTest_CONSTANTS_H

#include "DebugProtoTest_types.h"

namespace thrift { namespace test { namespace debug {

class DebugProtoTestConstants {
 public:
  DebugProtoTestConstants();

  CompactProtoTestStruct COMPACT_TEST;
  int32_t MYCONST;
  SomeEnum MY_SOME_ENUM;
  SomeEnum MY_SOME_ENUM_1;
  std::map<SomeEnum, SomeEnum>  MY_ENUM_MAP;
  std::map<SomeEnum, StructWithSomeEnum>  EXTRA_CRAZY_MAP;
};

extern const DebugProtoTestConstants g_DebugProtoTest_constants;

}}} // namespace

#endif
