/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef OptionalRequiredTest_CONSTANTS_H
#define OptionalRequiredTest_CONSTANTS_H

#include "OptionalRequiredTest_types.h"

namespace thrift { namespace test {

class OptionalRequiredTestConstants {
 public:
  OptionalRequiredTestConstants();

};

extern const OptionalRequiredTestConstants g_OptionalRequiredTest_constants;

}} // namespace

#endif
