/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "OptionalRequiredTest_constants.h"

namespace thrift { namespace test {

const OptionalRequiredTestConstants g_OptionalRequiredTest_constants;

OptionalRequiredTestConstants::OptionalRequiredTestConstants() {
}

}} // namespace

