/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ServiceForExceptionWithAMap_H
#define ServiceForExceptionWithAMap_H

#include <TProcessor.h>
#include "DebugProtoTest_types.h"

namespace thrift { namespace test { namespace debug {

class ServiceForExceptionWithAMapIf {
 public:
  virtual ~ServiceForExceptionWithAMapIf() {}
  virtual void methodThatThrowsAnException() = 0;
};

class ServiceForExceptionWithAMapNull : virtual public ServiceForExceptionWithAMapIf {
 public:
  virtual ~ServiceForExceptionWithAMapNull() {}
  void methodThatThrowsAnException() {
    return;
  }
};

class ServiceForExceptionWithAMap_methodThatThrowsAnException_args {
 public:

  ServiceForExceptionWithAMap_methodThatThrowsAnException_args() {
  }

  virtual ~ServiceForExceptionWithAMap_methodThatThrowsAnException_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  bool operator == (const ServiceForExceptionWithAMap_methodThatThrowsAnException_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ServiceForExceptionWithAMap_methodThatThrowsAnException_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceForExceptionWithAMap_methodThatThrowsAnException_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ServiceForExceptionWithAMap_methodThatThrowsAnException_pargs {
 public:


  virtual ~ServiceForExceptionWithAMap_methodThatThrowsAnException_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ServiceForExceptionWithAMap_methodThatThrowsAnException_result {
 public:

  ServiceForExceptionWithAMap_methodThatThrowsAnException_result() {
  }

  virtual ~ServiceForExceptionWithAMap_methodThatThrowsAnException_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  ExceptionWithAMap xwamap;

  struct __isset {
    __isset() : xwamap(false) {}
    bool xwamap;
  } __isset;

  bool operator == (const ServiceForExceptionWithAMap_methodThatThrowsAnException_result & rhs) const
  {
    if (!(xwamap == rhs.xwamap))
      return false;
    return true;
  }
  bool operator != (const ServiceForExceptionWithAMap_methodThatThrowsAnException_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceForExceptionWithAMap_methodThatThrowsAnException_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ServiceForExceptionWithAMap_methodThatThrowsAnException_presult {
 public:


  virtual ~ServiceForExceptionWithAMap_methodThatThrowsAnException_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  ExceptionWithAMap xwamap;

  struct __isset {
    __isset() : xwamap(false) {}
    bool xwamap;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ServiceForExceptionWithAMapClient : virtual public ServiceForExceptionWithAMapIf {
 public:
  ServiceForExceptionWithAMapClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ServiceForExceptionWithAMapClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void methodThatThrowsAnException();
  void send_methodThatThrowsAnException();
  void recv_methodThatThrowsAnException();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServiceForExceptionWithAMapProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<ServiceForExceptionWithAMapIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (ServiceForExceptionWithAMapProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*)> processMap_;
  void process_methodThatThrowsAnException(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
 public:
  ServiceForExceptionWithAMapProcessor(boost::shared_ptr<ServiceForExceptionWithAMapIf> iface) :
    iface_(iface) {
    processMap_["methodThatThrowsAnException"] = &ServiceForExceptionWithAMapProcessor::process_methodThatThrowsAnException;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot);
  virtual ~ServiceForExceptionWithAMapProcessor() {}
};

class ServiceForExceptionWithAMapMultiface : virtual public ServiceForExceptionWithAMapIf {
 public:
  ServiceForExceptionWithAMapMultiface(std::vector<boost::shared_ptr<ServiceForExceptionWithAMapIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServiceForExceptionWithAMapMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ServiceForExceptionWithAMapIf> > ifaces_;
  ServiceForExceptionWithAMapMultiface() {}
  void add(boost::shared_ptr<ServiceForExceptionWithAMapIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void methodThatThrowsAnException() {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->methodThatThrowsAnException();
    }
  }

};

}}} // namespace

#endif
