/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ThriftTest_H
#define ThriftTest_H

#include <TProcessor.h>
#include "ThriftTest_types.h"

namespace thrift { namespace test {

class ThriftTestIf {
 public:
  virtual ~ThriftTestIf() {}
  virtual void testVoid() = 0;
  virtual void testString(std::string& _return, const std::string& thing) = 0;
  virtual int8_t testByte(const int8_t thing) = 0;
  virtual int32_t testI32(const int32_t thing) = 0;
  virtual int64_t testI64(const int64_t thing) = 0;
  virtual double testDouble(const double thing) = 0;
  virtual void testStruct(Xtruct& _return, const Xtruct& thing) = 0;
  virtual void testNest(Xtruct2& _return, const Xtruct2& thing) = 0;
  virtual void testMap(std::map<int32_t, int32_t> & _return, const std::map<int32_t, int32_t> & thing) = 0;
  virtual void testSet(std::set<int32_t> & _return, const std::set<int32_t> & thing) = 0;
  virtual void testList(std::vector<int32_t> & _return, const std::vector<int32_t> & thing) = 0;
  virtual Numberz testEnum(const Numberz thing) = 0;
  virtual UserId testTypedef(const UserId thing) = 0;
  virtual void testMapMap(std::map<int32_t, std::map<int32_t, int32_t> > & _return, const int32_t hello) = 0;
  virtual void testInsanity(std::map<UserId, std::map<Numberz, Insanity> > & _return, const Insanity& argument) = 0;
  virtual void testMulti(Xtruct& _return, const int8_t arg0, const int32_t arg1, const int64_t arg2, const std::map<int16_t, std::string> & arg3, const Numberz arg4, const UserId arg5) = 0;
  virtual void testException(const std::string& arg) = 0;
  virtual void testMultiException(Xtruct& _return, const std::string& arg0, const std::string& arg1) = 0;
  virtual void testOneway(const int32_t secondsToSleep) = 0;
};

class ThriftTestNull : virtual public ThriftTestIf {
 public:
  virtual ~ThriftTestNull() {}
  void testVoid() {
    return;
  }
  void testString(std::string& /* _return */, const std::string& /* thing */) {
    return;
  }
  int8_t testByte(const int8_t /* thing */) {
    int8_t _return = 0;
    return _return;
  }
  int32_t testI32(const int32_t /* thing */) {
    int32_t _return = 0;
    return _return;
  }
  int64_t testI64(const int64_t /* thing */) {
    int64_t _return = 0;
    return _return;
  }
  double testDouble(const double /* thing */) {
    double _return = (double)0;
    return _return;
  }
  void testStruct(Xtruct& /* _return */, const Xtruct& /* thing */) {
    return;
  }
  void testNest(Xtruct2& /* _return */, const Xtruct2& /* thing */) {
    return;
  }
  void testMap(std::map<int32_t, int32_t> & /* _return */, const std::map<int32_t, int32_t> & /* thing */) {
    return;
  }
  void testSet(std::set<int32_t> & /* _return */, const std::set<int32_t> & /* thing */) {
    return;
  }
  void testList(std::vector<int32_t> & /* _return */, const std::vector<int32_t> & /* thing */) {
    return;
  }
  Numberz testEnum(const Numberz /* thing */) {
    Numberz _return = (Numberz)0;
    return _return;
  }
  UserId testTypedef(const UserId /* thing */) {
    UserId _return = 0;
    return _return;
  }
  void testMapMap(std::map<int32_t, std::map<int32_t, int32_t> > & /* _return */, const int32_t /* hello */) {
    return;
  }
  void testInsanity(std::map<UserId, std::map<Numberz, Insanity> > & /* _return */, const Insanity& /* argument */) {
    return;
  }
  void testMulti(Xtruct& /* _return */, const int8_t /* arg0 */, const int32_t /* arg1 */, const int64_t /* arg2 */, const std::map<int16_t, std::string> & /* arg3 */, const Numberz /* arg4 */, const UserId /* arg5 */) {
    return;
  }
  void testException(const std::string& /* arg */) {
    return;
  }
  void testMultiException(Xtruct& /* _return */, const std::string& /* arg0 */, const std::string& /* arg1 */) {
    return;
  }
  void testOneway(const int32_t /* secondsToSleep */) {
    return;
  }
};

class ThriftTest_testVoid_args {
 public:

  ThriftTest_testVoid_args() {
  }

  virtual ~ThriftTest_testVoid_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  bool operator == (const ThriftTest_testVoid_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftTest_testVoid_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testVoid_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testVoid_pargs {
 public:


  virtual ~ThriftTest_testVoid_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testVoid_result {
 public:

  ThriftTest_testVoid_result() {
  }

  virtual ~ThriftTest_testVoid_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  bool operator == (const ThriftTest_testVoid_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ThriftTest_testVoid_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testVoid_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testVoid_presult {
 public:


  virtual ~ThriftTest_testVoid_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testString_args {
 public:

  ThriftTest_testString_args() : thing("") {
  }

  virtual ~ThriftTest_testString_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::string thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testString_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testString_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testString_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testString_pargs {
 public:


  virtual ~ThriftTest_testString_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::string* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testString_result {
 public:

  ThriftTest_testString_result() : success("") {
  }

  virtual ~ThriftTest_testString_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::string success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testString_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testString_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testString_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testString_presult {
 public:


  virtual ~ThriftTest_testString_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::string* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testByte_args {
 public:

  ThriftTest_testByte_args() : thing(0) {
  }

  virtual ~ThriftTest_testByte_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int8_t thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testByte_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testByte_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testByte_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testByte_pargs {
 public:


  virtual ~ThriftTest_testByte_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int8_t* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testByte_result {
 public:

  ThriftTest_testByte_result() : success(0) {
  }

  virtual ~ThriftTest_testByte_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int8_t success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testByte_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testByte_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testByte_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testByte_presult {
 public:


  virtual ~ThriftTest_testByte_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int8_t* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testI32_args {
 public:

  ThriftTest_testI32_args() : thing(0) {
  }

  virtual ~ThriftTest_testI32_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testI32_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testI32_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testI32_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI32_pargs {
 public:


  virtual ~ThriftTest_testI32_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int32_t* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI32_result {
 public:

  ThriftTest_testI32_result() : success(0) {
  }

  virtual ~ThriftTest_testI32_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testI32_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testI32_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testI32_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI32_presult {
 public:


  virtual ~ThriftTest_testI32_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testI64_args {
 public:

  ThriftTest_testI64_args() : thing(0) {
  }

  virtual ~ThriftTest_testI64_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int64_t thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testI64_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testI64_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testI64_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI64_pargs {
 public:


  virtual ~ThriftTest_testI64_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int64_t* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI64_result {
 public:

  ThriftTest_testI64_result() : success(0) {
  }

  virtual ~ThriftTest_testI64_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int64_t success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testI64_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testI64_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testI64_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testI64_presult {
 public:


  virtual ~ThriftTest_testI64_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int64_t* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testDouble_args {
 public:

  ThriftTest_testDouble_args() : thing(0) {
  }

  virtual ~ThriftTest_testDouble_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  double thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testDouble_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testDouble_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testDouble_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testDouble_pargs {
 public:


  virtual ~ThriftTest_testDouble_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const double* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testDouble_result {
 public:

  ThriftTest_testDouble_result() : success(0) {
  }

  virtual ~ThriftTest_testDouble_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  double success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testDouble_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testDouble_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testDouble_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testDouble_presult {
 public:


  virtual ~ThriftTest_testDouble_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  double* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testStruct_args {
 public:

  ThriftTest_testStruct_args() {
  }

  virtual ~ThriftTest_testStruct_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testStruct_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testStruct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testStruct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testStruct_pargs {
 public:


  virtual ~ThriftTest_testStruct_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const Xtruct* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testStruct_result {
 public:

  ThriftTest_testStruct_result() {
  }

  virtual ~ThriftTest_testStruct_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testStruct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testStruct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testStruct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testStruct_presult {
 public:


  virtual ~ThriftTest_testStruct_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testNest_args {
 public:

  ThriftTest_testNest_args() {
  }

  virtual ~ThriftTest_testNest_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct2 thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testNest_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testNest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testNest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testNest_pargs {
 public:


  virtual ~ThriftTest_testNest_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const Xtruct2* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testNest_result {
 public:

  ThriftTest_testNest_result() {
  }

  virtual ~ThriftTest_testNest_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct2 success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testNest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testNest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testNest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testNest_presult {
 public:


  virtual ~ThriftTest_testNest_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct2* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testMap_args {
 public:

  ThriftTest_testMap_args() {
  }

  virtual ~ThriftTest_testMap_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<int32_t, int32_t>  thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testMap_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMap_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMap_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMap_pargs {
 public:


  virtual ~ThriftTest_testMap_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::map<int32_t, int32_t> * thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMap_result {
 public:

  ThriftTest_testMap_result() {
  }

  virtual ~ThriftTest_testMap_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<int32_t, int32_t>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testMap_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMap_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMap_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMap_presult {
 public:


  virtual ~ThriftTest_testMap_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<int32_t, int32_t> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testSet_args {
 public:

  ThriftTest_testSet_args() {
  }

  virtual ~ThriftTest_testSet_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::set<int32_t>  thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testSet_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testSet_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testSet_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testSet_pargs {
 public:


  virtual ~ThriftTest_testSet_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::set<int32_t> * thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testSet_result {
 public:

  ThriftTest_testSet_result() {
  }

  virtual ~ThriftTest_testSet_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::set<int32_t>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testSet_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testSet_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testSet_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testSet_presult {
 public:


  virtual ~ThriftTest_testSet_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::set<int32_t> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testList_args {
 public:

  ThriftTest_testList_args() {
  }

  virtual ~ThriftTest_testList_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::vector<int32_t>  thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testList_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testList_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testList_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testList_pargs {
 public:


  virtual ~ThriftTest_testList_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::vector<int32_t> * thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testList_result {
 public:

  ThriftTest_testList_result() {
  }

  virtual ~ThriftTest_testList_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::vector<int32_t>  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testList_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testList_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testList_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testList_presult {
 public:


  virtual ~ThriftTest_testList_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::vector<int32_t> * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testEnum_args {
 public:

  ThriftTest_testEnum_args() {
  }

  virtual ~ThriftTest_testEnum_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Numberz thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testEnum_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testEnum_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testEnum_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testEnum_pargs {
 public:


  virtual ~ThriftTest_testEnum_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const Numberz* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testEnum_result {
 public:

  ThriftTest_testEnum_result() {
  }

  virtual ~ThriftTest_testEnum_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Numberz success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testEnum_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testEnum_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testEnum_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testEnum_presult {
 public:


  virtual ~ThriftTest_testEnum_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Numberz* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testTypedef_args {
 public:

  ThriftTest_testTypedef_args() : thing(0) {
  }

  virtual ~ThriftTest_testTypedef_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  UserId thing;

  struct __isset {
    __isset() : thing(false) {}
    bool thing;
  } __isset;

  bool operator == (const ThriftTest_testTypedef_args & rhs) const
  {
    if (!(thing == rhs.thing))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testTypedef_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testTypedef_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testTypedef_pargs {
 public:


  virtual ~ThriftTest_testTypedef_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const UserId* thing;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testTypedef_result {
 public:

  ThriftTest_testTypedef_result() : success(0) {
  }

  virtual ~ThriftTest_testTypedef_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  UserId success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testTypedef_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testTypedef_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testTypedef_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testTypedef_presult {
 public:


  virtual ~ThriftTest_testTypedef_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  UserId* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testMapMap_args {
 public:

  ThriftTest_testMapMap_args() : hello(0) {
  }

  virtual ~ThriftTest_testMapMap_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t hello;

  struct __isset {
    __isset() : hello(false) {}
    bool hello;
  } __isset;

  bool operator == (const ThriftTest_testMapMap_args & rhs) const
  {
    if (!(hello == rhs.hello))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMapMap_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMapMap_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMapMap_pargs {
 public:


  virtual ~ThriftTest_testMapMap_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int32_t* hello;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMapMap_result {
 public:

  ThriftTest_testMapMap_result() {
  }

  virtual ~ThriftTest_testMapMap_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<int32_t, std::map<int32_t, int32_t> >  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testMapMap_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMapMap_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMapMap_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMapMap_presult {
 public:


  virtual ~ThriftTest_testMapMap_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<int32_t, std::map<int32_t, int32_t> > * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testInsanity_args {
 public:

  ThriftTest_testInsanity_args() {
  }

  virtual ~ThriftTest_testInsanity_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Insanity argument;

  struct __isset {
    __isset() : argument(false) {}
    bool argument;
  } __isset;

  bool operator == (const ThriftTest_testInsanity_args & rhs) const
  {
    if (!(argument == rhs.argument))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testInsanity_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testInsanity_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testInsanity_pargs {
 public:


  virtual ~ThriftTest_testInsanity_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const Insanity* argument;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testInsanity_result {
 public:

  ThriftTest_testInsanity_result() {
  }

  virtual ~ThriftTest_testInsanity_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<UserId, std::map<Numberz, Insanity> >  success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testInsanity_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testInsanity_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testInsanity_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testInsanity_presult {
 public:


  virtual ~ThriftTest_testInsanity_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<UserId, std::map<Numberz, Insanity> > * success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testMulti_args {
 public:

  ThriftTest_testMulti_args() : arg0(0), arg1(0), arg2(0), arg5(0) {
  }

  virtual ~ThriftTest_testMulti_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int8_t arg0;
  int32_t arg1;
  int64_t arg2;
  std::map<int16_t, std::string>  arg3;
  Numberz arg4;
  UserId arg5;

  struct __isset {
    __isset() : arg0(false), arg1(false), arg2(false), arg3(false), arg4(false), arg5(false) {}
    bool arg0;
    bool arg1;
    bool arg2;
    bool arg3;
    bool arg4;
    bool arg5;
  } __isset;

  bool operator == (const ThriftTest_testMulti_args & rhs) const
  {
    if (!(arg0 == rhs.arg0))
      return false;
    if (!(arg1 == rhs.arg1))
      return false;
    if (!(arg2 == rhs.arg2))
      return false;
    if (!(arg3 == rhs.arg3))
      return false;
    if (!(arg4 == rhs.arg4))
      return false;
    if (!(arg5 == rhs.arg5))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMulti_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMulti_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMulti_pargs {
 public:


  virtual ~ThriftTest_testMulti_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int8_t* arg0;
  const int32_t* arg1;
  const int64_t* arg2;
  const std::map<int16_t, std::string> * arg3;
  const Numberz* arg4;
  const UserId* arg5;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMulti_result {
 public:

  ThriftTest_testMulti_result() {
  }

  virtual ~ThriftTest_testMulti_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  bool operator == (const ThriftTest_testMulti_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMulti_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMulti_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMulti_presult {
 public:


  virtual ~ThriftTest_testMulti_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct* success;

  struct __isset {
    __isset() : success(false) {}
    bool success;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testException_args {
 public:

  ThriftTest_testException_args() : arg("") {
  }

  virtual ~ThriftTest_testException_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::string arg;

  struct __isset {
    __isset() : arg(false) {}
    bool arg;
  } __isset;

  bool operator == (const ThriftTest_testException_args & rhs) const
  {
    if (!(arg == rhs.arg))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testException_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testException_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testException_pargs {
 public:


  virtual ~ThriftTest_testException_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::string* arg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testException_result {
 public:

  ThriftTest_testException_result() {
  }

  virtual ~ThriftTest_testException_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xception err1;

  struct __isset {
    __isset() : err1(false) {}
    bool err1;
  } __isset;

  bool operator == (const ThriftTest_testException_result & rhs) const
  {
    if (!(err1 == rhs.err1))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testException_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testException_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testException_presult {
 public:


  virtual ~ThriftTest_testException_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xception err1;

  struct __isset {
    __isset() : err1(false) {}
    bool err1;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testMultiException_args {
 public:

  ThriftTest_testMultiException_args() : arg0(""), arg1("") {
  }

  virtual ~ThriftTest_testMultiException_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::string arg0;
  std::string arg1;

  struct __isset {
    __isset() : arg0(false), arg1(false) {}
    bool arg0;
    bool arg1;
  } __isset;

  bool operator == (const ThriftTest_testMultiException_args & rhs) const
  {
    if (!(arg0 == rhs.arg0))
      return false;
    if (!(arg1 == rhs.arg1))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMultiException_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMultiException_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMultiException_pargs {
 public:


  virtual ~ThriftTest_testMultiException_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const std::string* arg0;
  const std::string* arg1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMultiException_result {
 public:

  ThriftTest_testMultiException_result() {
  }

  virtual ~ThriftTest_testMultiException_result() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct success;
  Xception err1;
  Xception2 err2;

  struct __isset {
    __isset() : success(false), err1(false), err2(false) {}
    bool success;
    bool err1;
    bool err2;
  } __isset;

  bool operator == (const ThriftTest_testMultiException_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(err1 == rhs.err1))
      return false;
    if (!(err2 == rhs.err2))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testMultiException_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testMultiException_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testMultiException_presult {
 public:


  virtual ~ThriftTest_testMultiException_presult() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  Xtruct* success;
  Xception err1;
  Xception2 err2;

  struct __isset {
    __isset() : success(false), err1(false), err2(false) {}
    bool success;
    bool err1;
    bool err2;
  } __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ThriftTest_testOneway_args {
 public:

  ThriftTest_testOneway_args() : secondsToSleep(0) {
  }

  virtual ~ThriftTest_testOneway_args() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t secondsToSleep;

  struct __isset {
    __isset() : secondsToSleep(false) {}
    bool secondsToSleep;
  } __isset;

  bool operator == (const ThriftTest_testOneway_args & rhs) const
  {
    if (!(secondsToSleep == rhs.secondsToSleep))
      return false;
    return true;
  }
  bool operator != (const ThriftTest_testOneway_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTest_testOneway_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTest_testOneway_pargs {
 public:


  virtual ~ThriftTest_testOneway_pargs() throw() {}

  static ::apache::thrift::reflection::local::TypeSpec* local_reflection;

  const int32_t* secondsToSleep;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ThriftTestClient : virtual public ThriftTestIf {
 public:
  ThriftTestClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ThriftTestClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void testVoid();
  void send_testVoid();
  void recv_testVoid();
  void testString(std::string& _return, const std::string& thing);
  void send_testString(const std::string& thing);
  void recv_testString(std::string& _return);
  int8_t testByte(const int8_t thing);
  void send_testByte(const int8_t thing);
  int8_t recv_testByte();
  int32_t testI32(const int32_t thing);
  void send_testI32(const int32_t thing);
  int32_t recv_testI32();
  int64_t testI64(const int64_t thing);
  void send_testI64(const int64_t thing);
  int64_t recv_testI64();
  double testDouble(const double thing);
  void send_testDouble(const double thing);
  double recv_testDouble();
  void testStruct(Xtruct& _return, const Xtruct& thing);
  void send_testStruct(const Xtruct& thing);
  void recv_testStruct(Xtruct& _return);
  void testNest(Xtruct2& _return, const Xtruct2& thing);
  void send_testNest(const Xtruct2& thing);
  void recv_testNest(Xtruct2& _return);
  void testMap(std::map<int32_t, int32_t> & _return, const std::map<int32_t, int32_t> & thing);
  void send_testMap(const std::map<int32_t, int32_t> & thing);
  void recv_testMap(std::map<int32_t, int32_t> & _return);
  void testSet(std::set<int32_t> & _return, const std::set<int32_t> & thing);
  void send_testSet(const std::set<int32_t> & thing);
  void recv_testSet(std::set<int32_t> & _return);
  void testList(std::vector<int32_t> & _return, const std::vector<int32_t> & thing);
  void send_testList(const std::vector<int32_t> & thing);
  void recv_testList(std::vector<int32_t> & _return);
  Numberz testEnum(const Numberz thing);
  void send_testEnum(const Numberz thing);
  Numberz recv_testEnum();
  UserId testTypedef(const UserId thing);
  void send_testTypedef(const UserId thing);
  UserId recv_testTypedef();
  void testMapMap(std::map<int32_t, std::map<int32_t, int32_t> > & _return, const int32_t hello);
  void send_testMapMap(const int32_t hello);
  void recv_testMapMap(std::map<int32_t, std::map<int32_t, int32_t> > & _return);
  void testInsanity(std::map<UserId, std::map<Numberz, Insanity> > & _return, const Insanity& argument);
  void send_testInsanity(const Insanity& argument);
  void recv_testInsanity(std::map<UserId, std::map<Numberz, Insanity> > & _return);
  void testMulti(Xtruct& _return, const int8_t arg0, const int32_t arg1, const int64_t arg2, const std::map<int16_t, std::string> & arg3, const Numberz arg4, const UserId arg5);
  void send_testMulti(const int8_t arg0, const int32_t arg1, const int64_t arg2, const std::map<int16_t, std::string> & arg3, const Numberz arg4, const UserId arg5);
  void recv_testMulti(Xtruct& _return);
  void testException(const std::string& arg);
  void send_testException(const std::string& arg);
  void recv_testException();
  void testMultiException(Xtruct& _return, const std::string& arg0, const std::string& arg1);
  void send_testMultiException(const std::string& arg0, const std::string& arg1);
  void recv_testMultiException(Xtruct& _return);
  void testOneway(const int32_t secondsToSleep);
  void send_testOneway(const int32_t secondsToSleep);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ThriftTestProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<ThriftTestIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid);
 private:
  std::map<std::string, void (ThriftTestProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*)> processMap_;
  void process_testVoid(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testString(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testByte(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testI32(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testI64(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testDouble(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testStruct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testNest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testMap(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testSet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testList(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testEnum(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testTypedef(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testMapMap(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testInsanity(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testMulti(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testException(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testMultiException(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
  void process_testOneway(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot);
 public:
  ThriftTestProcessor(boost::shared_ptr<ThriftTestIf> iface) :
    iface_(iface) {
    processMap_["testVoid"] = &ThriftTestProcessor::process_testVoid;
    processMap_["testString"] = &ThriftTestProcessor::process_testString;
    processMap_["testByte"] = &ThriftTestProcessor::process_testByte;
    processMap_["testI32"] = &ThriftTestProcessor::process_testI32;
    processMap_["testI64"] = &ThriftTestProcessor::process_testI64;
    processMap_["testDouble"] = &ThriftTestProcessor::process_testDouble;
    processMap_["testStruct"] = &ThriftTestProcessor::process_testStruct;
    processMap_["testNest"] = &ThriftTestProcessor::process_testNest;
    processMap_["testMap"] = &ThriftTestProcessor::process_testMap;
    processMap_["testSet"] = &ThriftTestProcessor::process_testSet;
    processMap_["testList"] = &ThriftTestProcessor::process_testList;
    processMap_["testEnum"] = &ThriftTestProcessor::process_testEnum;
    processMap_["testTypedef"] = &ThriftTestProcessor::process_testTypedef;
    processMap_["testMapMap"] = &ThriftTestProcessor::process_testMapMap;
    processMap_["testInsanity"] = &ThriftTestProcessor::process_testInsanity;
    processMap_["testMulti"] = &ThriftTestProcessor::process_testMulti;
    processMap_["testException"] = &ThriftTestProcessor::process_testException;
    processMap_["testMultiException"] = &ThriftTestProcessor::process_testMultiException;
    processMap_["testOneway"] = &ThriftTestProcessor::process_testOneway;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot);
  virtual ~ThriftTestProcessor() {}
};

class ThriftTestMultiface : virtual public ThriftTestIf {
 public:
  ThriftTestMultiface(std::vector<boost::shared_ptr<ThriftTestIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ThriftTestMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ThriftTestIf> > ifaces_;
  ThriftTestMultiface() {}
  void add(boost::shared_ptr<ThriftTestIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void testVoid() {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->testVoid();
    }
  }

  void testString(std::string& _return, const std::string& thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testString(_return, thing);
        return;
      } else {
        ifaces_[i]->testString(_return, thing);
      }
    }
  }

  int8_t testByte(const int8_t thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testByte(thing);
      } else {
        ifaces_[i]->testByte(thing);
      }
    }
  }

  int32_t testI32(const int32_t thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testI32(thing);
      } else {
        ifaces_[i]->testI32(thing);
      }
    }
  }

  int64_t testI64(const int64_t thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testI64(thing);
      } else {
        ifaces_[i]->testI64(thing);
      }
    }
  }

  double testDouble(const double thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testDouble(thing);
      } else {
        ifaces_[i]->testDouble(thing);
      }
    }
  }

  void testStruct(Xtruct& _return, const Xtruct& thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testStruct(_return, thing);
        return;
      } else {
        ifaces_[i]->testStruct(_return, thing);
      }
    }
  }

  void testNest(Xtruct2& _return, const Xtruct2& thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testNest(_return, thing);
        return;
      } else {
        ifaces_[i]->testNest(_return, thing);
      }
    }
  }

  void testMap(std::map<int32_t, int32_t> & _return, const std::map<int32_t, int32_t> & thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testMap(_return, thing);
        return;
      } else {
        ifaces_[i]->testMap(_return, thing);
      }
    }
  }

  void testSet(std::set<int32_t> & _return, const std::set<int32_t> & thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testSet(_return, thing);
        return;
      } else {
        ifaces_[i]->testSet(_return, thing);
      }
    }
  }

  void testList(std::vector<int32_t> & _return, const std::vector<int32_t> & thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testList(_return, thing);
        return;
      } else {
        ifaces_[i]->testList(_return, thing);
      }
    }
  }

  Numberz testEnum(const Numberz thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testEnum(thing);
      } else {
        ifaces_[i]->testEnum(thing);
      }
    }
  }

  UserId testTypedef(const UserId thing) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->testTypedef(thing);
      } else {
        ifaces_[i]->testTypedef(thing);
      }
    }
  }

  void testMapMap(std::map<int32_t, std::map<int32_t, int32_t> > & _return, const int32_t hello) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testMapMap(_return, hello);
        return;
      } else {
        ifaces_[i]->testMapMap(_return, hello);
      }
    }
  }

  void testInsanity(std::map<UserId, std::map<Numberz, Insanity> > & _return, const Insanity& argument) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testInsanity(_return, argument);
        return;
      } else {
        ifaces_[i]->testInsanity(_return, argument);
      }
    }
  }

  void testMulti(Xtruct& _return, const int8_t arg0, const int32_t arg1, const int64_t arg2, const std::map<int16_t, std::string> & arg3, const Numberz arg4, const UserId arg5) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testMulti(_return, arg0, arg1, arg2, arg3, arg4, arg5);
        return;
      } else {
        ifaces_[i]->testMulti(_return, arg0, arg1, arg2, arg3, arg4, arg5);
      }
    }
  }

  void testException(const std::string& arg) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->testException(arg);
    }
  }

  void testMultiException(Xtruct& _return, const std::string& arg0, const std::string& arg1) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->testMultiException(_return, arg0, arg1);
        return;
      } else {
        ifaces_[i]->testMultiException(_return, arg0, arg1);
      }
    }
  }

  void testOneway(const int32_t secondsToSleep) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      ifaces_[i]->testOneway(secondsToSleep);
    }
  }

};

}} // namespace

#endif
