/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ThriftTest_CONSTANTS_H
#define ThriftTest_CONSTANTS_H

#include "ThriftTest_types.h"

namespace thrift { namespace test {

class ThriftTestConstants {
 public:
  ThriftTestConstants();

};

extern const ThriftTestConstants g_ThriftTest_constants;

}} // namespace

#endif
