/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hbase_constants.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

const hbaseConstants g_hbase_constants;

hbaseConstants::hbaseConstants() {
}

}}}} // namespace

