/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hbase_CONSTANTS_H
#define hbase_CONSTANTS_H

#include "hbase_types.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

class hbaseConstants {
 public:
  hbaseConstants();

};

extern const hbaseConstants g_hbase_constants;

}}}} // namespace

#endif
